# mybatis 配置
mybatis:
  mapper-locations: "classpath:mapper/**/*Dao.xml"

# Tomcat
server:
  connection-timeout: 5000
  port: 8082
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 1234
    url: "jdbc:mysql://localhost:3306/attendance-system?useUnicode=true&&useSSL=false&&characterEncoding=UTF-8&&serverTimezone=GMT%2B8"
    username: root
